version: "3.9"

services:
  frontend:
    container_name: accounter_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Frontend runs on port 3000
    environment:
      - API_URL=http://backend:5000 # Point frontend to backend
    env_file:
      - ./frontend/.env # Frontend-specific .env file
    depends_on:
      - backend # Ensure backend is ready before frontend starts

  backend:
    container_name: accounter_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env # Backend-specific .env file
    ports:
      - "5001:5000" # Backend runs on port 5000
    volumes:
      - ./backend:/app # Mount backend code for live updates (optional)
    depends_on:
      - db

  db:
    # Database service (POSTGRES_HOST)
    container_name: hetzner_db
    image: postgres:14
    env_file:
      - ./backend/.env # Use an environment file for sensitive values
    ports:
      - "5432:5432"
    volumes:
      - hetzner:/var/lib/postgresql/data # Persist database data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Mount init.sql for initialization

volumes:
  hetzner:


