version: "3.9"

services:
  frontend:
    container_name: accounter_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Frontend runs on port 3000
    environment:
      - API_URL=http://backend:5000  # Point frontend to backend
    depends_on:
      - backend  # Ensure backend is ready before frontend starts

  backend:
    container_name: accounter_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Backend runs on port 5000
    environment:
      - PROJECT_ID=your_project_id  # Replace with actual value
      - DATABASE_URL=postgresql://user:password@db:5432/accounter_db  # Point backend to database
    volumes:
      - ./backend:/app  # Mount backend code for live updates (optional)
    depends_on:
      - db
  
  db:
    container_name: accounter_db
    image: postgres:14
    environment:
      - POSTGRES_USER=user  # Replace with actual value
      - POSTGRES_PASSWORD=password  # Replace with actual value
      - POSTGRES_DB=accounter_db  # Replace with actual value
    ports:
      - "5432:5432"  # Database runs on port 5432
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist database data
  
volumes:
  db-data:
